apiVersion: core.rukpak.io/v1alpha2
kind: BundleDeployment
metadata:
  name: bd-v1test
spec:
  format: registry
  sources:
    - kind: git
      git:
        ref:
          branch: main
        repository: https://github.com/varshaprasad96/prometheus-rukpak
    - kind: git
      git:
        ref:
          branch: main
        repository: https://github.com/varshaprasad96/prometheus-rukpak-manifests

